"""Render docs/achievements.md from the catalogue.

Run from the repository root after adding, removing or renaming an
achievement:

    python3 tools/achievement-doc.py

`apps/beatbyte/tests/docs_stay_true.rs` fails if the document and the
catalogue disagree, so this is the way to fix that test rather than
editing the table by hand. The data-source column is the one thing
this script knows that the catalogue does not: which field of
`PlayEntry` / `RunDetail` / `RunPart` each `Test`, `Metric` and
`Facet` reads. A new variant needs a row in `SOURCE` below, or its
achievements will print an em dash and the reader will not know what
the rule is looking at.
"""
import re, sys

src = open("crates/beatbyte-core/src/achievements.rs").read()
body = src.split("pub const CATALOGUE: &[Achievement] = &[", 1)[1]
body = body.split("\n];", 1)[0]

# Split on the top-level `Achievement {` blocks.
blocks = re.findall(r"    Achievement \{(.*?)\n    \},", body, re.S)
assert len(blocks) == 100, len(blocks)

# Every field a Test / Metric / Facet reads, named as the log stores it.
SOURCE = {
    "Finished": "PlayEntry.completed",
    "MinAccuracy": "RunPart.accuracy",
    "MinStreak": "RunDetail.best_streak",
    "IsDifficulty": "PlayEntry.difficulty",
    "MinDifficulty": "PlayEntry.difficulty",
    "NoMiss": "RunDetail.miss",
    "NoOverstrum": "RunDetail.overstrums",
    "MaxDriftMs": "RunDetail.mean_offset_ms",
    "MinNotes": "RunDetail.perfect/great/good/miss",
    "MinOverstrums": "RunDetail.overstrums",
    "MoreOverstrumsThanHits": "RunDetail.overstrums + perfect/great/good",
    "MinTrackS": "PlayEntry.track_s",
    "NoPractice": "PlayEntry.practice",
    "NoTapAssist": "PlayEntry.tap_mode",
    "NoSafetyNet": "PlayEntry.no_fail",
    "DidFail": "RunDetail.failed",
    "MinHype": "RunDetail.hype_activations",
    "MinSustainsHeld": "RunDetail.sustains_held",
    "NoSustainDropped": "RunDetail.sustains_dropped",
    "MinPerfectShare": "RunDetail.perfect + judged()",
    "TitleAny": "PlayEntry.title",
    "TitleStartsWith": "PlayEntry.title",
    "OnDate": "PlayEntry.started_ms",
    "OnDates": "PlayEntry.started_ms",
    "HourIn": "PlayEntry.started_ms",
    "OnWeekday": "PlayEntry.started_ms",
    "FromFile": "PlayEntry.source",
    "AccuracyIsExactly": "RunPart.accuracy",
    "Runs": "PlayEntry (one per run)",
    "Finished_M": "PlayEntry.completed",
    "Seconds": "PlayEntry.played_s",
    "NotesHit": "RunDetail.perfect/great/good",
    "Perfects": "RunDetail.perfect",
    "Score": "RunPart.score",
    "HypeActivations": "RunDetail.hype_activations",
    "Phrases": "RunDetail.phrases_completed",
    "Song": "PlayEntry.title + artist",
    "Artist": "PlayEntry.artist",
    "Genre": "PlayEntry.genre",
    "Month": "PlayEntry.started_ms",
    "Days": "PlayEntry.started_ms",
    "DayStreak": "PlayEntry.started_ms",
    "SameSong": "PlayEntry.title + artist + completed",
    "SameSongInARow": "PlayEntry.title + artist",
    "AllDifficulties": "PlayEntry.difficulty + completed",
    "Sitting": "PlayEntry.started_ms",
    "Improved": "RunPart.accuracy + title/artist/difficulty",
    "Comeback": "PlayEntry.started_ms",
    "Redemption": "RunDetail.failed + PlayEntry.completed",
}

def field(name):
    return name.split("(", 1)[0].split(" ", 1)[0]

rows = []
for block in blocks:
    def grab(key):
        m = re.search(rf'{key}: (.*?),\n', block)
        return m.group(1).strip() if m else ""
    ident = grab("id").strip('"')
    title = grab("title").strip('"')
    blurb = grab("blurb").strip('"')
    category = grab("category").replace("Category::", "")
    tier = grab("tier").replace("Tier::", "")
    hidden = grab("hidden") == "true"
    rule_text = block.split("rule: ", 1)[1]
    # Which sources this rule reads.
    seen, order = set(), []
    for token in re.findall(r"Test::(\w+)|Metric::(\w+)|Facet::(\w+)|Rule::(\w+)", rule_text):
        name = next(t for t in token if t)
        key = "Finished_M" if (name == "Finished" and "Metric::Finished" in rule_text
                               and "Test::Finished" not in rule_text) else name
        source = SOURCE.get(key)
        if source and source not in seen:
            seen.add(source)
            order.append(source)
    rows.append((ident, title, blurb, category, tier, hidden, order))

rows.sort(key=lambda r: r[0])

out = []
out.append("# The achievement catalogue")
out.append("")
out.append("Generated by `tools/achievement-doc.py` from")
out.append("`crates/beatbyte-core/src/achievements.rs`, which is the only")
out.append("definition. `apps/beatbyte/tests/docs_stay_true.rs` fails if this")
out.append("file and that array ever disagree about which achievements exist —")
out.append("so read this, change that, and run the script.")
out.append("")
out.append("**Every row names the field its rule actually reads.** Eight of those")
out.append("fields were added to the play log for this feature (a ninth,")
out.append("`speed_percent`, is recorded but read by no rule yet) and all are")
out.append("optional: a run recorded before them reads as *not recorded*, never")
out.append("as a zero. A rule cannot credit a run that cannot answer it.")
out.append("")
out.append("**Hidden rows are secret in the game, not here.** This file is the")
out.append("engineering reference; the screen shows `? ? ?`, no description and")
out.append("no progress bar until the achievement is earned.")
out.append("")
out.append(f"{len(rows)} achievements, {sum(1 for r in rows if r[5])} of them hidden.")
out.append("")
out.append("| ID | Title | Condition | Category | Tier | Hidden | Data source |")
out.append("|---|---|---|---|---|:-:|---|")
for ident, title, blurb, category, tier, hidden, order in rows:
    src_col = " · ".join(f"`{s}`" for s in order) or "—"
    out.append(f"| `{ident}` | {title} | {blurb} | {category} | {tier} | "
               f"{'yes' if hidden else ''} | {src_col} |")
out.append("")
open("docs/achievements.md", "w").write("\n".join(out) + "\n")
print(f"{len(rows)} rows written")
