// WebMCP tools: lets an AI agent in the browser ask this page for facts and actions directly instead of
// scraping it (https://developer.chrome.com/docs/ai/webmcp). Only registered where the browser offers
// `modelContext`; everywhere else this file does nothing. All data comes from the same places the page
// uses — latest.json and changelog.md on this origin — so tools and page can never disagree.
(function () {
  'use strict';

  var mc = (typeof document !== 'undefined' && document.modelContext) ||
    (typeof navigator !== 'undefined' && navigator.modelContext);
  if (!mc || typeof mc.registerTool !== 'function') return;

  // Facts from site.json (generated by build.py).
  var FACTS = {
    "name": "BeatByte",
    "summary": "BeatByte is a free, open-source (MIT) five-lane rhythm game for macOS, Windows and Linux, written in Rust. It turns the player's own music files into playable charts in four difficulties, shows karaoke lyrics, runs on a 3D concert stage, and plays with a keyboard, gamepads or a guitar controller, for one to four local players. No song ships with the game; nothing is uploaded.",
    "requirements": {
      "macos": "macOS 11+ · Apple silicon",
      "macos-intel": "macOS 11+ · Intel",
      "windows": "Windows 10/11 · 64-bit · portable zip",
      "linux-appimage": "Linux · x86_64"
    },
    "platforms": [
      "Keyboard",
      "Gamepad",
      "Guitar controller",
      "MP3 · M4A · FLAC · OGG · WAV",
      "2–4 players"
    ],
    "features": [
      "Automatic charts from your own music in four difficulties",
      "Add a song by name (with yt-dlp installed)",
      "Karaoke lyrics from lrclib or your own .lrc file",
      "3D concert stage with lights, crowd and effects",
      "Keyboard, gamepads and a native Guitar Hero X-plorer driver",
      "Local multiplayer for two to four players",
      "In-game latency calibration and practice mode",
      "Built-in chart editor",
      "Three hundred achievements and per-player statistics"
    ],
    "limits": [
      "No songs ship with the game; you bring your own music",
      "Generated charts are playable, not hand-authored; the editor is the correction pass",
      "No online multiplayer",
      "No mobile or web version",
      "The macOS builds are not notarized: open them once with right-click → Open",
      "Xbox 360 wireless guitars are not supported on macOS"
    ],
    "targets": [
      "macos",
      "macos-intel",
      "windows",
      "linux-appimage"
    ],
    "signing": [],
    "links": {
      "page": "https://beatbyte.celox.io/",
      "download": "https://beatbyte.celox.io/download",
      "latest": "https://beatbyte.celox.io/latest.json",
      "markdown": "https://beatbyte.celox.io/index.md",
      "changelog": "https://beatbyte.celox.io/changelog.md",
      "skill": "https://beatbyte.celox.io/skills/get-beatbyte/SKILL.md",
      "source": "https://github.com/pepperonas/beatbyte",
      "licence": "https://github.com/pepperonas/beatbyte/blob/main/LICENSE"
    }
  };
  var SITE = FACTS.links.page.replace(/\/$/, '');
  var LANGS = ["en", "de", "es", "it", "fr"];

  function latest(signal) {
    return fetch('/latest.json', { cache: 'no-cache', signal: signal }).then(function (r) {
      if (!r.ok) throw new Error('latest.json: HTTP ' + r.status);
      return r.json();
    });
  }
  function json(v) { return JSON.stringify(v, null, 2); }
  var READ = { readOnlyHint: true };

  var tools = [
    {
      name: 'get_app_facts',
      description: 'What BeatByte is: a one-paragraph summary, requirements, supported platforms, ' +
        'features, limits and the important links (download, source, changelog, licence).',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function () { return Promise.resolve(json(FACTS)); }
    },
    {
      name: 'get_latest_release',
      description: 'The newest release of BeatByte: version, publication date, release notes URL ' +
        'and every file with its download URL, size in bytes and SHA-256.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          return json({ version: d.version, published: d.published, notes: d.notes, assets: d.assets ||
            [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size, sha256: d.sha256 }] });
        });
      }
    },
    {
      name: 'get_download_url',
      description: 'The direct download URL of the newest BeatByte file for a platform (macos, macos-intel, windows, linux-appimage), plus ' +
        'the stable link that always redirects to the newest file.',
      inputSchema: {
        type: 'object',
        properties: { platform: { type: 'string', enum: FACTS.targets, description: 'Target platform; default: ' + FACTS.targets[0] + '.' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ target: FACTS.targets[0], name: d.name, url: d.url, size: d.size }];
          var want = (input && input.platform) || assets[0].target;
          var a = assets.filter(function (x) { return x.target === want; })[0] || assets[0];
          return json({ version: d.version, platform: a.target, file: a.name, url: a.url, size: a.size,
            stable_link: SITE + '/download/' + a.target });
        });
      }
    },
    {
      name: 'get_checksums',
      description: 'How to verify a downloaded BeatByte file: the SHA-256 of every file of the newest release ' +
        'and the fixed signing facts.',
      inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      annotations: READ,
      execute: function (_input, opts) {
        return latest(opts && opts.signal).then(function (d) {
          var assets = d.assets || [{ name: d.name, sha256: d.sha256 }];
          return json({ version: d.version,
            files: assets.map(function (a) { return { name: a.name, sha256: a.sha256 }; }),
            signing: FACTS.signing });
        });
      }
    },
    {
      name: 'get_changelog',
      description: 'The most recent entries of the BeatByte changelog as Markdown.',
      inputSchema: {
        type: 'object',
        properties: { versions: { type: 'integer', minimum: 1, maximum: 10, description: 'How many versions (default 3).' } },
        additionalProperties: false
      },
      annotations: READ,
      execute: function (input, opts) {
        var n = Math.min(10, Math.max(1, (input && input.versions) || 3));
        return fetch('/changelog.md', { cache: 'no-cache', signal: opts && opts.signal }).then(function (r) {
          if (!r.ok) throw new Error('changelog.md: HTTP ' + r.status);
          return r.text();
        }).then(function (md) {
          var parts = md.split(/\n(?=## \[)/).slice(1).filter(function (s) { return !/^## \[Unreleased\]\s*$/.test(s.trim()); });
          return parts.slice(0, n).join('\n').trim();
        });
      }
    },
    {
      name: 'set_page_language',
      description: 'Show this page in another language (English, German, Spanish, Italian or French).',
      inputSchema: {
        type: 'object',
        properties: { language: { type: 'string', enum: LANGS, description: 'ISO 639-1 code.' } },
        required: ['language'],
        additionalProperties: false
      },
      annotations: { readOnlyHint: false },
      execute: function (input) {
        if (LANGS.indexOf(input.language) < 0) throw new Error('unsupported language: ' + input.language);
        if (typeof window.SITE_setLanguage === 'function') window.SITE_setLanguage(input.language);
        return Promise.resolve('Page language set to ' + input.language + '.');
      }
    }
  ];

  tools.forEach(function (t) {
    try { mc.registerTool(t); } catch (e) { /* a browser with an older WebMCP shape: skip that tool */ }
  });
})();
